# web table 
# Jekyll web table Generator

####################
# Site Settings
#
title: Sheets Demo
# header and head metadata
description: "Demo using google sheets with CollectionBuilder static web stack" 
# site domain, on GH-pages, following pattern https://yourusername.github.io
url: https://evanwill.github.io
# location on the domain
# on GH-pages the repository name, /yourreponame
baseurl: /table-sheet-test
# location of code (repository link)
source-code: https://github.com/evanwill/table-sheet-test

# ID number of your google sheet
google-sheet-id: 1dUAPI7nge5PWTksdUITA9IbgA_Csz2gtVSCnjWz1CjE

####################
# Table Config
#
# columns, where field = the exact column name on google sheets
table-columns: 
  - field: title
    display_name: Title
  - field: date
    display_name: Date
  - field: creator
    display_name: Creator
  - field: subject
    display_name: Subjects
# column to sort on, 0 to number of columns [optional]
sort-column: 1
# order of sort, either asc or desc [optional]
sort-order: desc

####################
# Cloud Config
#
# field to create a cloud from
cloud-field: subject
# stopwords to remove from cloud, ";" separated list [optional]
# not working right now!
cloud-stopwords: the;he

# Technical stuff
exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
